// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Cliente struct {
	ID     int32  `db:"id"`
	Nome   string `db:"nome"`
	Saldo  int32  `db:"saldo"`
	Limite int32  `db:"limite"`
}

type Transaco struct {
	ID          int32     `db:"id"`
	ClienteID   int32     `db:"cliente_id"`
	Valor       int32     `db:"valor"`
	Tipo        string    `db:"tipo"`
	Descricao   string    `db:"descricao"`
	RealizadaEm time.Time `db:"realizada_em"`
}
